version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    requirements-file: "requirements.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    requirements-file: "requirements-dev.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    requirements-file: "requirements-ml.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
