---
deployment:
  tasks:
    - export VENV_DIR="${HOME}/python-venv"
    - if [ ! -d "$VENV_DIR" ]; then python3 -m venv $VENV_DIR; fi
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install -r conf/requirements.txt
    # Adicione aqui comandos extras, como migrar banco ou reiniciar serviços
