[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["src", "tests", "scripts"]
skip = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".env",
    "build",
    "dist",
    "*.egg-info",
    ".pytest_cache",
    "node_modules"
]

[tool.autopep8]
max_line_length = 88
ignore = ["E203", "E501", "W503", "W504"]