# 🚀 AUDITORIA360 - Streamlit Cloud Deployment Configuration

[build]
# Python version for Streamlit Cloud
python = "3.11"

[dependencies]
# Main requirements file
file = "dashboards/requirements.txt"

[run]
# Main application file
app_file = "dashboards/app.py"

[server]
# Server configuration
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Theme configuration (matches .streamlit/config.toml)
base = "dark"
primaryColor = "#1e2327"
backgroundColor = "#111315"
secondaryBackgroundColor = "#23272b"
textColor = "#f5f5f5"
font = "sans serif"

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[global]
# Global settings
developmentMode = false
logLevel = "info"
unitTest = false
showErrorDetails = false
suppressDeprecationWarnings = true