-- /migrations/003_criar_tabela_parametros_legais.sql
-- Tabela para armazenar os dados estruturados extraídos pela IA
-- NOTA: Execute após a migração 004_criar_tabela_documentos.sql

-- Create ParametrosLegais table
CREATE TABLE IF NOT EXISTS public."ParametrosLegais" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES public."Documentos"(id) ON DELETE CASCADE,
    
    nome_parametro TEXT NOT NULL,       -- Ex: 'aliquota_inss_faixa_1', 'valor_salario_familia'
    valor_parametro TEXT NOT NULL,      -- Ex: '7.5', '59.82'
    tipo_valor TEXT NOT NULL,           -- Ex: 'percentual', 'moeda', 'inteiro'
    contexto_original TEXT,             -- O trecho do texto de onde a informação foi extraída
    data_inicio_vigencia DATE,          -- Quando este parâmetro entra em vigor
    data_fim_vigencia DATE,             -- Quando este parâmetro deixa de ser válido (opcional)
    
    criado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Criar um índice para acelerar as consultas por nome de parâmetro e vigência
CREATE INDEX IF NOT EXISTS idx_parametros_legais_nome_vigencia 
ON public."ParametrosLegais" (nome_parametro, data_inicio_vigencia DESC);

-- Índice adicional para consultas por documento
CREATE INDEX IF NOT EXISTS idx_parametros_legais_documento_id 
ON public."ParametrosLegais" (documento_id);

COMMENT ON TABLE public."ParametrosLegais" IS 'Tabela para armazenar parâmetros legais estruturados extraídos pela IA';
COMMENT ON COLUMN public."ParametrosLegais".nome_parametro IS 'Nome identificador do parâmetro (ex: aliquota_inss_faixa_1)';
COMMENT ON COLUMN public."ParametrosLegais".valor_parametro IS 'Valor do parâmetro como string (ex: 7.5, 1550.00)';
COMMENT ON COLUMN public."ParametrosLegais".tipo_valor IS 'Tipo do valor: percentual, moeda, inteiro, texto';
COMMENT ON COLUMN public."ParametrosLegais".contexto_original IS 'Trecho original do texto de onde o parâmetro foi extraído';