-- /migrations/004_criar_tabela_documentos.sql
-- Tabela para armazenar documentos submetidos para processamento

CREATE TABLE IF NOT EXISTS public."Documentos" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,                     -- Nome do arquivo original
    texto_extraido TEXT,                    -- Texto extraído do documento
    status TEXT DEFAULT 'PROCESSANDO',      -- PROCESSANDO, CONCLUIDO, ERRO
    tipo_documento TEXT,                    -- PDF, DOC, etc. (opcional)
    tamanho_bytes BIGINT,                   -- Tamanho do arquivo em bytes (opcional)
    
    criado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    atualizado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_documentos_status ON public."Documentos" (status);
CREATE INDEX IF NOT EXISTS idx_documentos_criado_em ON public."Documentos" (criado_em DESC);

-- Trigger para atualizar atualizado_em automaticamente
CREATE OR REPLACE FUNCTION update_atualizado_em_documentos()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_atualizado_em_documentos
    BEFORE UPDATE ON public."Documentos"
    FOR EACH ROW
    EXECUTE FUNCTION update_atualizado_em_documentos();

COMMENT ON TABLE public."Documentos" IS 'Tabela para armazenar documentos legais submetidos para processamento e análise de IA';
COMMENT ON COLUMN public."Documentos".nome IS 'Nome original do arquivo submetido';
COMMENT ON COLUMN public."Documentos".texto_extraido IS 'Texto extraído do documento pela função processar-pdf';
COMMENT ON COLUMN public."Documentos".status IS 'Status atual do processamento: PROCESSANDO, CONCLUIDO, ERRO';