-- =====================================================================
-- SCRIPT DE EXPANSÃO DO SCHEMA - MÓDULO CCT E SINDICATOS
-- =====================================================================
-- Este script implementa o módulo de Gestão de Convenções Coletivas (CCTs) 
-- e Sindicatos conforme especificado na funcionalidade.

-- PASSO 1.1: Criar a tabela para armazenar os Sindicatos.
CREATE TABLE IF NOT EXISTS public."Sindicatos" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sindicato TEXT NOT NULL,
    cnpj TEXT UNIQUE,
    base_territorial TEXT, -- Ex: "São Paulo - SP"
    categoria_representada TEXT, -- Ex: "Trabalhadores no Comércio de Bens, Serviços e Turismo"
    criado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public."Sindicatos" IS 'Armazena os sindicatos laborais relevantes para os clientes.';

-- PASSO 1.2: Criar a tabela central para as Convenções Coletivas de Trabalho (CCTs).
CREATE TABLE IF NOT EXISTS public."ConvencoesColetivas" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sindicato_id BIGINT NOT NULL REFERENCES public."Sindicatos"(id) ON DELETE CASCADE,
    numero_registro_mte TEXT UNIQUE, -- Código único do Sistema Mediador do Governo
    vigencia_inicio DATE NOT NULL,
    vigencia_fim DATE NOT NULL,
    link_documento_oficial TEXT, -- URL para o PDF oficial no site do governo
    dados_cct JSONB, -- Campo flexível para armazenar os dados extraídos da CCT
    criado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public."ConvencoesColetivas" IS 'Armazena os dados das CCTs registadas no MTE.';
COMMENT ON COLUMN public."ConvencoesColetivas".dados_cct IS 'Estrutura JSON para guardar dados como pisos salariais, benefícios, etc.';

-- PASSO 1.3: Alterar a tabela de Empresas para ligá-la a um Sindicato.
ALTER TABLE public."Empresas"
ADD COLUMN IF NOT EXISTS sindicato_id BIGINT REFERENCES public."Sindicatos"(id) ON DELETE SET NULL;

COMMENT ON COLUMN public."Empresas".sindicato_id IS 'Associa a empresa cliente ao seu sindicato laboral correspondente.';

-- PASSO 1.4: Criar índices para acelerar as buscas.
CREATE INDEX IF NOT EXISTS idx_empresas_sindicato_id ON public."Empresas" (sindicato_id);
CREATE INDEX IF NOT EXISTS idx_convencoes_sindicato_id ON public."ConvencoesColetivas" (sindicato_id);

-- =====================================================================
-- IMPLEMENTAÇÃO DA SEGURANÇA (ROW LEVEL SECURITY)
-- =====================================================================

-- Habilitar RLS nas novas tabelas
ALTER TABLE public."Sindicatos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ConvencoesColetivas" ENABLE ROW LEVEL SECURITY;

-- Política para Sindicatos: só pode ver/gerir sindicatos que estão associados
-- a pelo menos uma empresa da sua carteira de clientes.
CREATE POLICY "Acesso a sindicatos das próprias empresas" ON public."Sindicatos"
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public."Empresas" e
    WHERE e.sindicato_id = "Sindicatos".id
    AND e.contabilidade_id = auth.get_contabilidade_id()
  )
);

-- Política para ConvencoesColetivas: só pode ver/gerir CCTs de sindicatos
-- que estão ligados a empresas da sua carteira.
CREATE POLICY "Acesso a CCTs dos próprios sindicatos" ON public."ConvencoesColetivas"
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public."Sindicatos" s
    JOIN public."Empresas" e ON e.sindicato_id = s.id
    WHERE s.id = "ConvencoesColetivas".sindicato_id
    AND e.contabilidade_id = auth.get_contabilidade_id()
  )
);

-- =====================================================================
-- FIM DO SCRIPT DE EXPANSÃO
-- =====================================================================