-- =====================================================================
-- MIGRAÇÃO 008: TEMPLATES DE CONTROLE MENSAL
-- =====================================================================
-- Esta migração adiciona as tabelas necessárias para a funcionalidade de
-- templates de tarefas recorrentes para controles mensais.
-- =====================================================================

-- Criar tabela para armazenar templates de controle
CREATE TABLE IF NOT EXISTS public."TemplatesControle" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contabilidade_id BIGINT NOT NULL REFERENCES public."Contabilidades"(id) ON DELETE CASCADE,
    nome_template TEXT NOT NULL,
    descricao TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(contabilidade_id, nome_template) -- Garante que não há templates com mesmo nome para a mesma contabilidade
);

-- Comentários da tabela
COMMENT ON TABLE public."TemplatesControle" IS 'Armazena modelos de tarefas para diferentes tipos de empresas (ex: Simples Nacional, Lucro Presumido).';
COMMENT ON COLUMN public."TemplatesControle".contabilidade_id IS 'Referência à empresa de contabilidade proprietária do template.';
COMMENT ON COLUMN public."TemplatesControle".nome_template IS 'Nome identificador do template (ex: "Simples Nacional - Padrão").';
COMMENT ON COLUMN public."TemplatesControle".descricao IS 'Descrição opcional do template e quando usá-lo.';

-- Criar tabela para armazenar as tarefas de cada template
CREATE TABLE IF NOT EXISTS public."TemplatesControle_Tarefas" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES public."TemplatesControle"(id) ON DELETE CASCADE,
    descricao_tarefa TEXT NOT NULL
);

-- Comentários da tabela
COMMENT ON TABLE public."TemplatesControle_Tarefas" IS 'Armazena as tarefas padrão que compõem cada template de controle.';
COMMENT ON COLUMN public."TemplatesControle_Tarefas".template_id IS 'Referência ao template ao qual esta tarefa pertence.';
COMMENT ON COLUMN public."TemplatesControle_Tarefas".descricao_tarefa IS 'Descrição da tarefa que será criada quando o template for aplicado.';

-- Criar índices para otimizar as consultas
CREATE INDEX IF NOT EXISTS idx_templates_controle_contabilidade_id ON public."TemplatesControle" (contabilidade_id);
CREATE INDEX IF NOT EXISTS idx_templates_tarefas_template_id ON public."TemplatesControle_Tarefas" (template_id);

-- Habilitar RLS (Row Level Security) nas novas tabelas para manter a segurança multi-tenant
ALTER TABLE public."TemplatesControle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TemplatesControle_Tarefas" ENABLE ROW LEVEL SECURITY;

-- Política para a tabela TemplatesControle - usuários só veem templates da sua contabilidade
CREATE POLICY "Acesso aos templates da contabilidade" ON public."TemplatesControle"
FOR ALL
USING (auth.get_contabilidade_id() = contabilidade_id)
WITH CHECK (auth.get_contabilidade_id() = contabilidade_id);

-- Política para a tabela TemplatesControle_Tarefas - via template
CREATE POLICY "Acesso às tarefas dos templates da contabilidade" ON public."TemplatesControle_Tarefas"
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public."TemplatesControle" tc
    WHERE tc.id = "TemplatesControle_Tarefas".template_id 
    AND tc.contabilidade_id = auth.get_contabilidade_id()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public."TemplatesControle" tc
    WHERE tc.id = "TemplatesControle_Tarefas".template_id 
    AND tc.contabilidade_id = auth.get_contabilidade_id()
  )
);

-- Inserir alguns templates de exemplo (opcional - apenas para demonstração)
-- Isso pode ser removido em produção se preferir começar sem dados de exemplo

INSERT INTO public."TemplatesControle" (contabilidade_id, nome_template, descricao)
VALUES
    (1, 'Simples Nacional - Padrão', 'Template padrão para empresas do Simples Nacional com tarefas básicas'),
    (1, 'Lucro Presumido - Completo', 'Template completo para empresas de Lucro Presumido com todas as obrigações'),
    (1, 'MEI - Simplificado', 'Template simplificado para Microempreendedores Individuais')
ON CONFLICT (contabilidade_id, nome_template) DO NOTHING;

-- Inserir tarefas padrão para os templates de exemplo
-- Template 1: Simples Nacional - Padrão
INSERT INTO public."TemplatesControle_Tarefas" (template_id, descricao_tarefa)
SELECT tc.id, tarefa.descricao
FROM public."TemplatesControle" tc,
     (VALUES 
        ('INFO_FOLHA'),
        ('ENVIO_CLIENTE'), 
        ('GUIA_FGTS'),
        ('DARF_INSS'),
        ('ESOCIAL_DCTFWEB')
     ) AS tarefa(descricao)
WHERE tc.nome_template = 'Simples Nacional - Padrão' AND tc.contabilidade_id = 1;

-- Template 2: Lucro Presumido - Completo  
INSERT INTO public."TemplatesControle_Tarefas" (template_id, descricao_tarefa)
SELECT tc.id, tarefa.descricao
FROM public."TemplatesControle" tc,
     (VALUES 
        ('INFO_FOLHA'),
        ('ENVIO_CLIENTE'), 
        ('GUIA_FGTS'),
        ('DARF_INSS'),
        ('ESOCIAL_DCTFWEB'),
        ('APURACAO_IRPJ'),
        ('APURACAO_CSLL'),
        ('DARF_IRPJ_CSLL'),
        ('SPED_FISCAL'),
        ('SPED_CONTRIBUICOES')
     ) AS tarefa(descricao)
WHERE tc.nome_template = 'Lucro Presumido - Completo' AND tc.contabilidade_id = 1;

-- Template 3: MEI - Simplificado
INSERT INTO public."TemplatesControle_Tarefas" (template_id, descricao_tarefa)
SELECT tc.id, tarefa.descricao  
FROM public."TemplatesControle" tc,
     (VALUES 
        ('INFO_FOLHA'),
        ('ENVIO_CLIENTE'),
        ('DAS_MEI')
     ) AS tarefa(descricao)
WHERE tc.nome_template = 'MEI - Simplificado' AND tc.contabilidade_id = 1;

-- =====================================================================
-- FIM DA MIGRAÇÃO 008
-- =====================================================================