project_id: "meu-projeto-gcp"
environment: "development"
region: "us-central1"
bq_dataset: "auditoria_folha_dataset"
input_bucket: "auditoria-folha-input-pdfs"
output_bucket: "auditoria-folha-processed-pdfs"

retry:
  attempts: 5
  wait_seconds: 2
