credentials:
  usernames:
    admin:
      email: contato@empresa.com.br
      name: Admin
      password: pbkdf2:sha256:260000$senha_fake
      contabilidade: ADMIN
      role: ADMIN
cookie:
  name: auditoria_cookie
  key: segredo_seguro
  expiry_days: 7
