apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria360-api
  labels:
    app: auditoria360-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auditoria360-api
  template:
    metadata:
      labels:
        app: auditoria360-api
        tier: backend
    spec:
      containers:
      - name: auditoria360-api
        image: auditoria360/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auditoria360-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: auditoria360-secrets
              key: redis-url
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: auditoria360-secrets
              key: r2-access-key
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: auditoria360-secrets
              key: r2-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: auditoria360-api-service
  labels:
    app: auditoria360-api
spec:
  selector:
    app: auditoria360-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auditoria360-api-hpa
  labels:
    app: auditoria360-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auditoria360-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditoria360-config
  labels:
    app: auditoria360
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REDIS_TTL_DEFAULT: "300"
  CACHE_ENABLED: "true"
  PERFORMANCE_MONITORING: "true"
  MAX_WORKERS: "4"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auditoria360-api-pdb
  labels:
    app: auditoria360-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: auditoria360-api