name: CI

on:
  pull_request:
    branches: [ main, copilot/* ]
  push:
    branches: [ main, copilot/* ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          pytest --maxfail=1 --disable-warnings
      - name: Rodar lint
        run: |
          pip install flake8
          flake8 src/ automation/ portal_demandas/
      - name: Cobertura
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
