
# Workflow oficial para Deploy Automático do Frontend no GitHub Pages
name: Deploy Frontend to GitHub Pages (Oficial)

on:
  push:
    branches:
      - Principal
    paths:
      - 'src/frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/deploy-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: |
          cd src/frontend
          npm install

      - name: Build do frontend
        run: |
          cd src/frontend
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
