# Workflow for automatic deployment of the frontend to GitHub Pages
name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - Principal
    paths:
      - 'src/frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/gh-pages-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd src/frontend
          npm install

      - name: Build frontend
        run: |
          cd src/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/frontend/dist
          publish_branch: gh-pages
          cname: CNAME
          force_orphan: true
